application:
  title: @project.name@
  version: @project.version@

bookshelf:
  owner: Max Mustermann
  isbn-lookup:
    server-uri: http://example.com/isbn

spring:
  jpa:
    defer-datasource-initialization: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
  sql:
    init:
      mode: always
